# Generated by Django 5.1.3 on 2024-11-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desk', '0001_initial'),
        ('report', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdesk',
            name='desk_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_head', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='reportdesk',
            name='national_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_editor', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='reportdesk',
            name='regional_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_editor', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='reportdesk',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report'),
        ),
        migrations.AddField(
            model_name='reportdesk',
            name='zonal_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonal_editor', to='staff.staff'),
        ),
    ]
