# Generated by Django 5.1.3 on 2024-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('EDITOR', 'Editor'), ('REPORTER', 'Reporter'), ('DESK_HEAD', 'Desk Head'), ('REGIONAL_EDITOR', 'Regional Editor'), ('NATIONAL_EDITOR', 'National Editor')], max_length=20)),
            ],
        ),
    ]
